/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package cn.edu.com;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENCESTATEMENT = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTCONDITIONALSTATEMENTS = 6;
  public int JJTLOGICCONDITION = 7;
  public int JJTCONDITION = 8;
  public int JJTLOOPSTATEMENT = 9;
  public int JJTSWITCHSTATEMENT = 10;
  public int JJTEXPRESSION = 11;
  public int JJTADDITIVEEXPRESSION = 12;
  public int JJTMULTIPLICATIVEEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTTYPE = 15;
  public int JJTRELATIONSHIP = 16;
  public int JJTLOGIC = 17;
  public int JJTRETURN = 18;
  public int JJTCREASE = 19;


  public String[] jjtNodeName = {
    "Start",
    "program",
    "Statementblock",
    "Statement",
    "SequenceStatement",
    "assignment",
    "Conditionalstatements",
    "Logiccondition",
    "Condition",
    "loopstatement",
    "SwitchStatement",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "type",
    "Relationship",
    "Logic",
    "Return",
    "crease",
  };
}
/* JavaCC - OriginalChecksum=3b03ee74eb1ce8f9d5dcad6e0f38b34e (do not edit this line) */
